### ISSUE TITLE
Fonts aren't loaded from Google Font server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/123done#110]
> GET https://themes.googleusercontent.com/static/fonts/opensans/v8/cJZKeOuBrn4kERxqtaUH3bO3LdcAZYWl9Si6vvxL-qU.woff [HTTP/1.1 200 OK 60ms]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://themes.googleusercontent.com/static/fonts/opensans/v8/cJZKeOuBrn4kERxqtaUH3bO3LdcAZYWl9Si6vvxL-qU.woff. This can be fixed by moving the resource to the same domain or enabling CORS.

Connect-fonts will fix this!

**Comment by vladikoff** [comment]
Not priority for now... Closing.
