### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [mozilla/123done#139]
The repo is public, but it's not easy to find out how I'm allowed to use or share the code. 

Could you add a LICENSE file to make it easier for users to understand how you'd like it to be used? 

http://choosealicense.com/ might be helpful here. 

Thanks!

**Comment by pdehaan** [comment]
@edunham This should be released under **MPL-2.0** license (per the /package.json file).
I added a LICENSE file and tweaked the package.json file in #140.

**Comment by edunham** [comment]
Awesome, thanks! I'll close this now and let the PR serve as the documentation :)
