### ISSUE TITLE
Prototype 123done as an OpenID Connect relier

### ISSUE THREAD

**Issue by rfk** [mozilla/123done#144]
To help us experiment with OpenID Connect in Firefox Accounts, let's make 123done a generic OpenID Connect relier.  We'll know our implementation is successful if we can do this using an off-the-shelf support library with no customizations specific to FxA.

**Comment by vladikoff** [comment]
@rfk @dannycoates so I was thinking about using Persona for our metrics dashboard, but then... What if use this OpenId login for it? (something to discuss in a meeting)

@dannycoates could you link to the changes you had to make for 123done to add this?

**Comment by vladikoff** [comment]
I got confused. Danny clarified that we should use https://github.com/dannycoates/123done/tree/google-auth
