### ISSUE TITLE
Failing to load http://beta.123done.org/

### ISSUE THREAD

**Issue by davehunt** [mozilla/123done#145]
Our [automated checks](https://webqa-ci.mozilla.com/view/BIDPOM/) for Persona are failing due to http://beta.123done.org/ failing to load. The loading spinner is displayed, and the login buttons are never shown.

First failure was noticed at [Nov 22, 2015 7:22:00 PM](https://webqa-ci.mozilla.com/view/BIDPOM/job/bidpom.stage/587/), last success was [24 hours earlier](https://webqa-ci.mozilla.com/view/BIDPOM/job/bidpom.stage/586/).

![screenshot 2015-11-23 11 01 22](https://cloud.githubusercontent.com/assets/122800/11335134/b672ad7a-91d1-11e5-9311-b0521074309a.png)

/cc @jrgm @m8ttyB @bobsilverberg

**Comment by jrgm** [comment]
The problem is that https://login.anosrep.org/include.js is returning 'HTTP/1.1 503 Service Unavailable: Back-end server is at capacity'. 

In other words, nothing is running at that URL. 

@relud - can you check what's up with this? Thanks.

**Comment by vladikoff** [comment]
https://login.anosrep.org/include.js is back!

**Comment by relud** [comment]
an auto-scaling failure caused the staging site to go offline. i manually auto-scaled it, and set it to automatically auto-scale unhealthy hosts in the future.
