### ISSUE TITLE
drop jwcrypto from the oauth branch

### ISSUE THREAD

**Issue by vladikoff** [mozilla/123done#147]
we are using RS here: https://github.com/mozilla/123done/blob/oauth/scripts/gen_keys.js#L48
for gen_keys. Can we use gen_keys from the fxa-auth-server?

@rfk @dannycoates thoughts?

**Comment by rfk** [comment]
Yes please!  IIRC we've also used [1] in other repos for a similar purpose.

[1] https://www.npmjs.com/package/generate-rsa-keypair

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/123done/commit/b93c94471464f19fbd43e9331fa2f394e29230ae
