### ISSUE TITLE
There does not seem to be any way to uncheck a checked item in the list

### ISSUE THREAD

**Issue by jbonacci** [mozilla/123done#23]
I created a list with a given account.
Then by clicking on any list time, I get a red x.
(this is through mouse/keyboard on desktop or by tablet)
I can not figure out how to uncheck an item
as a result I am mistakenly removing items from the list that I still want.
And, it is not clear how, if at all, I can sync back the original list.

**Comment by vladikoff** [comment]
Not priority for now... Closing.
