### ISSUE TITLE
Make font selectable or as part of the user profile

### ISSUE THREAD

**Issue by jbonacci** [mozilla/123done#25]
Although I am a big fan of the more creative font faces - like the current one in blue here - some people may find it a bit hard to read.
This does not really change the functionality of the site as a demo RP.
But if we want to make it more slick, we should think about giving the user a choice of supported (ie browser) font faces and colors.
Not too hard to do really.
Or, limit this to one sans, one serif, and the current creative with a choice of a few colors.

If we are going toward profile data per user and/or account, then font information could go there...

**Comment by vladikoff** [comment]
Not priority for now... Closing.
