### ISSUE TITLE
Android 4.x: After zoom in for list entry, screen is not redrawn

### ISSUE THREAD

**Issue by jbonacci** [mozilla/123done#26]
I noticed this with Android 4.x (ICS) on a phone.
I have not tried against other mobile devices yet.

If I tap in the list/item field, I get a zoom in and a keyboard pop-up, as expected.
After I type in an item and click Go, the item is added but I can not see it because I am still zoomed in on the text field.
I have to zoom out by hand to see the full 123done.org page with my list, buttons, etc.

**Comment by vladikoff** [comment]
Not priority for now... Closing.
