### ISSUE TITLE
Mobile: Icon and help text are not discoverable/selectable

### ISSUE THREAD

**Issue by jbonacci** [mozilla/123done#27]
I noticed this with my Android 4.x phone, but I will assume this is true for all mobile devices.

The icon in the upper right corner of the page (and to the left of the Sign In) button is visible, so therefore discoverable.
But its purpose is not discoverable!
I am unable to "hover over" the icon for obvious reasons, so there appears to be no way to bring up the help text.

Looks like we need a way to activate that icon as a button when using a mobile device, so that clicking on it brings up an info/help text.

**Comment by vladikoff** [comment]
Not priority for now... Closing.
