### ISSUE TITLE
Consider opening links in new tabs/pages

### ISSUE THREAD

**Issue by jbonacci** [mozilla/123done#35]
Right now the following links open over the current 123done.org session:
Fork me on GitHub
Persona
identity folks

This can be confusing if the user is logged in (with or without a list) and hits one of the links.
The user must go back to the original page to continue with the list.
If he/she closes the the tab/page - which is common on a mobile device, then the original 123done page must be reloaded.
This works out OK for now since the user will still be logged in.

But, this can get more confusing if the user clicks a link then starts navigating new content, possibly opening extra pages:
TOS or the developer page on diresworb.org
Commits or Branchs on GitHub

It is entirely possible to move far enough off of 123done.org to confuse the user in terms of getting back.

We should instead, open the links as new tabs/pages that can be navigated/bookmarked/closed separately...

**Comment by vladikoff** [comment]
Not priority for now... Closing.
