### ISSUE TITLE
Demo sites should have an RP icon

### ISSUE THREAD

**Issue by fmarier** [mozilla/123done#53]
To make it clear to people that see these demos that the dialog can be branded a bit, we should have an RP logo on this site.

Maybe this [public domain one](https://openclipart.org/detail/15820/-by--15820)?

![Checkbox](https://openclipart.org/image/250px/svg_to_png/15820/jetxee_check_sign_and_cross_sign_3.png)

**Comment by rfk** [comment]
Closing out some old persona-related bugs, doubling down on folding this demo RP into FxA development...
