### ISSUE TITLE
Site header doesnt look great on mobile (FxOS)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/123done#83]
Launch 123done.org on a Firefox OS device. The header word-wraps kind of awkwardly where "simplified" is on its own line.

![2013-09-10-16-52-05](https://f.cloud.github.com/assets/557895/1119405/f6ef59b0-1a74-11e3-8a28-f5d52990d1de.png)

**Comment by vladikoff** [comment]
Closing until needed
