### ISSUE TITLE
[oauth] /about.html isn't very pretty

### ISSUE THREAD

**Issue by pdehaan** [mozilla/123done#96]
Found in http://123done.dev.lcip.org/ver.txt (commit 7e65386)

```
7e65386 use deployed server config
```

---

### Steps to reproduce:
1. http://123done.dev.lcip.org/about.html (or click the "Learn more!" link at the bottom of http://123done.dev.lcip.org/)
2. MY EYES!

### Actual results:
My eyes are sad.

![123done_-_your_tasks__simplified](https://cloud.githubusercontent.com/assets/557895/2848250/41102b22-d0ba-11e3-93ea-6cfb70329d5c.png)
**Figure 1:** bad stuff.

Looks like we have a few 404s/errors:

| ERROR | PAGE | 
|----|----|
| GET [/css/bootstrap.css](http://123done.dev.lcip.org/css/bootstrap.css) 404 (Not Found) | about.html:11 |
| GET [/modernizr.min.js](http://123done.dev.lcip.org/modernizr.min.js) 404 (Not Found) | about.html:14 |
| GET [/css/bootstrap-responsive.css](http://123done.dev.lcip.org/css/bootstrap-responsive.css) 404 (Not Found) | about.html:12 |
| GET [/js/jquery.min.js](http://123done.dev.lcip.org/js/jquery.min.js) 404 (Not Found) | about.html:53 |
| Uncaught ReferenceError: $ is not defined | state.js:18 |
| Uncaught ReferenceError: $ is not defined | 123done.js:8 |

### Expected results:
Less sadness in my ocular area.

**Comment by vladikoff** [comment]
Not priority for now... Closing.
